
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 09 10:50:53 CEST 2019
//----------------------------------------------------

package de.bucherda.probabilistic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHOICE_C = 14;
  public static final int CLOSETAG = 51;
  public static final int EMPTY = 41;
  public static final int NOTALLOWED = 43;
  public static final int INTERLEAVE_O = 11;
  public static final int REF = 46;
  public static final int NAME_O = 36;
  public static final int PARAM = 55;
  public static final int INTERLEAVE_C = 12;
  public static final int ANYNAME_O = 32;
  public static final int DATA = 48;
  public static final int DEFINE = 29;
  public static final int GRAMMAR = 39;
  public static final int ZERO = 2;
  public static final int PARENTREF = 47;
  public static final int NAME_C = 37;
  public static final int MIXED_O = 25;
  public static final int ANYNAME_C = 33;
  public static final int ONEORMORE_O = 19;
  public static final int ENDTAG = 52;
  public static final int EOF = 0;
  public static final int MIXED_C = 26;
  public static final int error = 1;
  public static final int DATA_C = 31;
  public static final int NSNAME_O = 34;
  public static final int ONEORMORE_C = 20;
  public static final int EXCEPT_O = 27;
  public static final int NAME = 38;
  public static final int HEAD = 4;
  public static final int ZEROORMORE_O = 17;
  public static final int ATTRIBUTE_O = 7;
  public static final int GROUP_O = 9;
  public static final int ATTR = 56;
  public static final int ANYNAME = 50;
  public static final int NSNAME_C = 35;
  public static final int OPTIONAL_O = 15;
  public static final int EXTERNALREF = 49;
  public static final int EXCEPT_C = 28;
  public static final int QM = 3;
  public static final int ZEROORMORE_C = 18;
  public static final int LIST_O = 21;
  public static final int ELEMENT = 44;
  public static final int ATTRIBUTE_C = 8;
  public static final int GROUP_C = 10;
  public static final int OPTIONAL_C = 16;
  public static final int ELEMENT_O = 5;
  public static final int STRING = 53;
  public static final int START_O = 23;
  public static final int VALUE = 54;
  public static final int TEXT = 42;
  public static final int LIST_C = 22;
  public static final int CHOICE_O = 13;
  public static final int ATTRIBUTE = 45;
  public static final int DEFINE_C = 30;
  public static final int GRAMMAR_C = 40;
  public static final int ELEMENT_C = 6;
  public static final int START_C = 24;
}

